services:
  db:
    image: mysql:5.7
    restart: always
    container_name: webmanager_db
    environment:
      MYSQL_DATABASE: 'Devops'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - DB:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: webmanager_phpmyadmin
    restart: always
    ports:
      - "3333:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  node_test:
    container_name: webmanager_node
    restart: always
    depends_on:
      - phpmyadmin
    build: ./api
    ports: 
      - "3000:3000"

  nginx:
    build: ./homepage
    container_name: webmanager_nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - phpmyadmin
volumes:
  DB:

